version: '3.8'

services:
  admira-etl-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - ADS_API_URL=https://mocki.io/v1/9dcc2981-2bc8-465a-bce3-47767e1278e6
      - CRM_API_URL=https://mocki.io/v1/6a064f10-829d-432c-9f0d-24d5b8cb71c7
      - SINK_URL=https://httpbin.org/post
      - SINK_SECRET=admira_secret_example
      - PORT=8080
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    working_dir: /app
    command: go run main.go
    stdin_open: true
    tty: true

volumes:
  go-mod-cache:
